### PR TITLE
Clubhouse

### PR DESCRIPTION
**Pull request by Ferm0494**
Basic auth using devise for user and posts.
- Relation for posts and user ✅ 
- Applied methods of devise gem for auth ✅ 
- Deployed a live version to Heroku 💚

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @Ferm0494      
#### Great Job so far, but there are a few more things required. 
### General
- [ ] You should implement Users Controller
### UsersController
#### new action
 - [ ] it has a new action with User.new (screenshot from Pathwright)
#### create action
 - [ ] it has a create action. Must use user_params 
##### view

* [ ] It has a sign up form created with #form_for in `app/views/users`
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by Ferm0494** [comment]
@kobiyoyo  Actually the devise gem sets you up a view and a controller for User.

**Comment by Ferm0494** [comment]
Oding Project reqs: Let’s build those secrets! We’ll need to make sure only signed in users can see the author of each post. We’re not going to worry about editing or deleting posts.

Create a Post model and a Posts controller and a corresponding resource in your Routes file which allows the [:new, :create, :index] methods.
Atop your Posts Controller, use a #before_action to restrict access to the #new and #create methods to only users who are signed in. Create the necessary helper methods in your ApplicationController.
For your Posts Controller, prepare your #new action.
Write a very simple form in the app/views/posts/new.html.erb view which will create a new Post.
Make your corresponding #create action build a post where the foreign key for the author (e.g. user_id) is automatically populated based on whichever user is signed in. Redirect to the Index view if successful.
Fill out the #index action of the PostsController and create the corresponding view. The view should show a list of every post.
Now add logic in your Index view to display the author’s name, but only if a user is signed in.
Sign in and create a few secret posts.
Test it out – sign out and go to the index page. You should see a list of the posts but no author names. Sign in and the author names should appear. Your secrets are safe!

**Comment by Ferm0494** [comment]
@kobiyoyo Please feel free to check the live version https://clubhouse94.herokuapp.com/ to check the corresponding auths for User.

**Comment by Ferm0494** [comment]
Params were set in the application controller.

**Comment by Anna-Myzukina** [comment]
## Hi @Ferm0494  ! Very nice project! :wave: 

# You did a great job, approved  :+1:

### Go and merge to master.


`Goodluck in your next projects Happy coding ` <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Comment by Ferm0494** [comment]
Thank you for the review.

**Pull request merged**
